version: "3.2"
services:
  mysql:
    image: mysql:5.7.38
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
      - TZ=Asia/Tokyo